### PR TITLE
LintDiff: Ensure that default tag is scanned when there is a new tag in the 'after' state

### LINKED ISSUE #38492: [lint-diff] Crash during "correlating runs"
Should never happen:

```
Wed, 29 Oct 2025 17:07:35 GMT
Correlating runs...

Wed, 29 Oct 2025 17:07:35 GMT
Error: Process completed with exit code 1.
```

Run: https://github.com/Azure/azure-rest-api-specs-pr/actions/runs/18916089095/job/53999750310#step:7:7914

PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/25212

### PR DESCRIPTION
**Pull request by danieljurek**
Fixes https://github.com/Azure/azure-rest-api-specs/issues/38492 -- LintDiff should compare new tags to the previous default tag. 

The basic case covered by both old and new LintDiff: 

Before: 
  * tag-a -- default (already exists)
  * tag-b (already exists)
  * tag-c (already exists)

After:
  * tag-d (add a new tag) 

In this case, tag-c is compared with tag-a, the default tag

Both old and new LintDiff have gaps in coverage for the addition of a new tag in the presence of edited non-default tags: 

Before: 
  * tag-a -- default (already exists)
  * tag-b (already exists)
  * tag-c (already exists)

After:
  * tag-d (new tag) 
  * tag-b (edit tag-b)
  * tag-c (edit tag-c) 

In this case, we'll see error because the newly added tag-d has multiple possible correlation candidates (tag-b, tag-c) none of which are the default tag. Old LintDiff, by contrast, should have compared tag-d with tag-a (the way it would in the prior scenario) but it too can have undefined behavior in this case.

### CODE REVIEW

File: eng/tools/lint-diff/src/processChanges.ts [hunk 1]
```diff
@@ -205,6 +205,21 @@ export function reconcileChangedFilesAndTags(
...
+  // tag from before is included in scans
+  for (const [readme, afterTags] of afterFinal.entries()) {
+    if (!beforeFinal.has(readme)) {
+      continue;
+    }
+
+    const beforeTags = beforeFinal.get(readme)!.changedTags;
+    for (const tag of afterTags.changedTags) {
+      if (!beforeTags.has(tag)) {
+        beforeTags.add("");
```
Comment (mikeharder) [inline eng/tools/lint-diff/src/processChanges.ts:218]:
```suggestion
        beforeTags.add("");
        break;
```

Should we break after tag `""` is added once?  Or is there a reason to add it multiple times?

Comment (mikeharder) [reply eng/tools/lint-diff/src/processChanges.ts:218]: Is `""` a new sentinel value you're introducing in this PR?  Or was it already used internally to represent "default tag"?

If it's a new sentinel, we might want to choose something more identifiable, but also not valid as a normal tag name.  Maybe something like `__default`?

Comment (danieljurek) [reply eng/tools/lint-diff/src/processChanges.ts:218]: The empty string for tag effectively evaluates to "no tag" which means "default tag" to autorest. 

This evaluation in the code determines whether to add the `--tag` parameter so `""` meets the requirement there. 

```typescript
      if (tag) {
        autorestArgs.push(`--tag=${tag}`);
      }
```

https://github.com/Azure/azure-rest-api-specs/blob/main/eng/tools/lint-diff/src/runChecks.ts#L52-L54

In the past, I had used an empty set and coalesced it to `null` to get the same behavior. Now that you mention it, I can eliminate that coalescing and use an empty string as well... 

https://github.com/Azure/azure-rest-api-specs/blob/main/eng/tools/lint-diff/src/processChanges.ts#L151

Comment (danieljurek) [reply eng/tools/lint-diff/src/processChanges.ts:218]: If we did use a sentinel value it'd need to be something that would not be a valid tag like `<default>` or something

**Review by mikeharder — APPROVED** [review]
