### PR TITLE
[python] Update sdk-tspconfig-validation.ts

### LINKED ISSUE #35545: [BUG] We should not require specific values in certain language emitter configurations
### API Spec link

https://github.com/Azure/azure-rest-api-specs/pull/35533

### API Spec version

2024-12-09-preview

### Describe the bug

We should not be requiring folks to set `generate-test` and `generate-sample` to **true** for python emitter configuration options. There are many cases where folks will not want to have tests and samples generated for them. For example, brownfield or any already existing client library that already has full set of tests and samples and these new files just add noise and more work to remove every time they regenerate. 

We should carefully consider what configuration options need specific values and whether the value you want to enforce should actually be validated or not. 

Example CI failure: https://github.com/Azure/azure-rest-api-specs/actions/runs/15937786090/job/44961004885?pr=35533#step:4:192

### Expected behavior

We should be able to set `generate-test: false` without any additional work on the service partner side. 

### Actual behavior

Have to either turn the option to true or add a suppression.

### Reproduction Steps

See PR.

### Environment

_No response_

### PR DESCRIPTION
**Pull request by msyyc**
fix https://github.com/Azure/azure-rest-api-specs/issues/35545
For data-plane, it is not necessary to configure generate-test/generate-sample.

### CODE REVIEW

File: eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts [hunk 1]
```diff
@@ -437,6 +437,18 @@ export class TspConfigPythonMgmtPackageDirectorySubRule extends TspconfigEmitter
   }
 }
 
+export class TspConfigPythonMgmtPackageGenerateTestTrueSubRule extends TspconfigEmitterOptionsSubRuleBase {
+  constructor() {
+    super("@azure-tools/typespec-python", "generate-test", true);
+  }
+}
```
Comment (wanlwanl) [inline eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts:447]: Should skip dataplane?
```suggestion
protected skip(_: any, folder: string) {
    return skipForDataPlane(folder);
  }
}
```

File: eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts [hunk 2]
```diff
@@ -437,6 +437,18 @@ export class TspConfigPythonMgmtPackageDirectorySubRule extends TspconfigEmitter
...
+
+export class TspConfigPythonMgmtPackageGenerateSampleTrueSubRule extends TspconfigEmitterOptionsSubRuleBase {
+  constructor() {
+    super("@azure-tools/typespec-python", "generate-sample", true);
+  }
+}
```
Comment (wanlwanl) [inline eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts:456]: Should skip dataplane?

```suggestion
protected skip(_: any, folder: string) {
    return skipForDataPlane(folder);
  }
}
```

File: eng/tools/typespec-validation/test/sdk-tspconfig-validation.test.ts [hunk 3]
```diff
@@ -431,22 +431,22 @@ const pythonDpPackageDirTestCases = createEmitterOptionTestCases(
   [new TspConfigPythonDpPackageDirectorySubRule()],
 );
 
-const pythonAzGenerateTestTestCases = createEmitterOptionTestCases(
+const pythonMgmtPackageGenerateTestTestCases = createEmitterOptionTestCases(
```
Comment (wanlwanl) [inline eng/tools/typespec-validation/test/sdk-tspconfig-validation.test.ts]: Please remove this test for dataplane for required option

File: eng/tools/typespec-validation/test/sdk-tspconfig-validation.test.ts [hunk 4]
```diff
@@ -431,22 +431,22 @@ const pythonDpPackageDirTestCases = createEmitterOptionTestCases(
...
   "",
   "generate-test",
   true,
   false,
-  [new TspConfigPythonAzGenerateTestTrueSubRule()],
+  [new TspConfigPythonMgmtPackageGenerateTestTrueSubRule()],
 );
 
-const pythonAzGenerateSampleTestCases = createEmitterOptionTestCases(
+const pythonMgmtPackageGenerateSampleTestCases = createEmitterOptionTestCases(
```
Comment (wanlwanl) [inline eng/tools/typespec-validation/test/sdk-tspconfig-validation.test.ts]: Please remove this test for dataplane for required option

File: eng/tools/typespec-validation/test/sdk-tspconfig-validation.test.ts (hunk 3 above)
Comment (wanlwanl) [reply eng/tools/typespec-validation/test/sdk-tspconfig-validation.test.ts]: You can reuse `createEmitterOptionExample` to build tspconfig sample and test if dataplane is skipped

File: eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts [hunk 5]
```diff
@@ -437,35 +437,40 @@ export class TspConfigPythonMgmtPackageDirectorySubRule extends TspconfigEmitter
...
 }
 
-export class TspConfigPythonMgmtNamespaceSubRule extends TspconfigEmitterOptionsSubRuleBase {
+export class TspConfigPythonMgmtPackageGenerateTestTrueSubRule extends TspconfigEmitterOptionsSubRuleBase {
   constructor() {
-    super("@azure-tools/typespec-python", "namespace", new RegExp(/^azure\.mgmt(\.[a-z]+){1,2}$/));
+    super("@azure-tools/typespec-python", "generate-test", true);
   }
-  protected skip(_: any, folder: string) {
+protected skip(_: any, folder: string) {
```
Comment (wanlwanl) [inline eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts]: nit: please add intent

File: eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts [hunk 6]
```diff
@@ -437,35 +437,40 @@ export class TspConfigPythonMgmtPackageDirectorySubRule extends TspconfigEmitter
...
-// ----- Python data plane sub rules -----
-export class TspConfigPythonDpPackageDirectorySubRule extends TspconfigEmitterOptionsSubRuleBase {
+export class TspConfigPythonMgmtPackageGenerateSampleTrueSubRule extends TspconfigEmitterOptionsSubRuleBase {
   constructor() {
-    super("@azure-tools/typespec-python", "package-dir", new RegExp(/^azure(-[a-z]+){1,3}$/));
+    super("@azure-tools/typespec-python", "generate-sample", true);
   }
-  protected skip(_: any, folder: string) {
-    return skipForManagementPlane(folder);
+protected skip(_: any, folder: string) {
```
Comment (wanlwanl) [inline eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts]: nit: please add intent

**Review by wanlwanl — APPROVED** [review]

**Review by wanlwanl — APPROVED** [review]
