### PR TITLE
[TypeSpec Validation] Ensure "compile" and "format" rules fail if process returns error

### LINKED ISSUE #25453: [TypeSpec Validation] Check passed even though "tsp compile" reported error
In this run, `tsp compile` failed with this error, but the overall check `TypeSpec Validation` still passed.  This needs to be fixed ASAP to prevent PRs merging with this error.

```
run command:npx --no tsp compile . --warn-as-error
TypeSpec compiler v0.47.0

Diagnostics were reported during compilation:

error import-not-found: Couldn't resolve import "@azure-tools/typespec-providerhub-controller"

Found 1 error.
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3024862&view=logs&j=52599800-cfcd-5615-dd98-137d26e8cb9a&t=c0acbdc7-6ccc-5699-6c3a-c41428f73fe2&l=42

### PR DESCRIPTION
**Pull request by ckairen**
closes #25453

### CODE REVIEW

**Comment by ckairen** [comment]
past run for validating failed compilation & failed tsp format
https://dev.azure.com/azure-sdk/public/_build/results?buildId=3025690&view=logs&j=52599800-cfcd-5615-dd98-137d26e8cb9a&t=c0acbdc7-6ccc-5699-6c3a-c41428f73fe2&l=296

File: eng/tools/TypeSpecValidation/src/rules/format.ts [hunk 1]
```diff
@@ -8,9 +8,9 @@ export class FormatRule implements Rule {
 
   async execute(folder: string): Promise<RuleResult> {
     // Format parent folder to include shared files
-    let [stdOutput, errorOutput] = await runCmd(`npx tsp format ../**/*.tsp`, folder);
 
-    let success = errorOutput == null ? false : true;
+    let [err, stdOutput, errorOutput] = await runCmd(`npx tsp format ../**/*.tsp`, folder);
+    let success = err || errorOutput ? false : true;
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/rules/format.ts:13]: I believe we should only treat `errorOutput` as implying "Error" if we know a tool is buggy, like `tsp format`.  Add a comment explaining this with a link to the bug you opened against `tsp format`.

**Review by mikeharder — CHANGES_REQUESTED** [review]

File: eng/tools/TypeSpecValidation/src/rules/compile.ts [hunk 2]
```diff
@@ -13,22 +13,24 @@ export class CompileRule implements Rule {
...
     if (await checkFileExists(path.join(folder, "client.tsp"))) {
-      let [std, err] = await runCmd(
+      let [err, stdout, stderr] = await runCmd(
         `npx --no tsp compile client.tsp --no-emit --warn-as-error`,
         folder
       );
-      stdOutput += std;
-      if (err == null) {
+      stdOutput += stdout;
+      if (err || stderr) {
```
Comment (ckairen) [inline eng/tools/TypeSpecValidation/src/rules/compile.ts:30]:
```suggestion
      if (err ) {
```

File: eng/tools/TypeSpecValidation/src/rules/compile.ts [hunk 3]
```diff
@@ -13,22 +13,24 @@ export class CompileRule implements Rule {
     let errorOutput: string | undefined;
 
     if (await checkFileExists(path.join(folder, "main.tsp"))) {
-      let [std, err] = await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
-      stdOutput += std;
-      if (err == null) {
+      let [err, stdout, stderr] = await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
+      stdOutput += stdout;
+      if (err || stderr) {
```
Comment (ckairen) [inline eng/tools/TypeSpecValidation/src/rules/compile.ts:18]:
```suggestion
      if (err) {
```

File: eng/tools/TypeSpecValidation/src/rules/format.ts (hunk 1 above)
Comment (ckairen) [inline eng/tools/TypeSpecValidation/src/rules/format.ts:13]:
```suggestion
    // Failing on both err and errorOutput because of known bug in tsp format
    // https://github.com/microsoft/typespec/issues/2323
    let success = err || errorOutput ? false : true;
```

File: eng/tools/TypeSpecValidation/src/rules/compile.ts [hunk 4]
```diff
@@ -13,22 +13,24 @@ export class CompileRule implements Rule {
...
     if (await checkFileExists(path.join(folder, "client.tsp"))) {
-      let [std, err] = await runCmd(
+      let [err, stdout, stderr] = await runCmd(
         `npx --no tsp compile client.tsp --no-emit --warn-as-error`,
         folder
       );
-      stdOutput += std;
-      if (err == null) {
+      stdOutput += stdout;
+      if (err ) {
```
Comment (ckairen) [inline eng/tools/TypeSpecValidation/src/rules/compile.ts:30]:
```suggestion
      if (err) {
```

File: eng/tools/TypeSpecValidation/src/rules/compile.ts [hunk 5]
```diff
@@ -13,22 +13,24 @@ export class CompileRule implements Rule {
...
         folder
       );
-      stdOutput += std;
-      if (err == null) {
+      stdOutput += stdout;
+      if (err) {
         success = false;
-        errorOutput += err;
+        errorOutput += err.message;
+        errorOutput += stderr;
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/rules/compile.ts:33]:
```suggestion
        errorOutput += stderr;
        errorOutput += err.message;
```

In a console scenario, I believe you would see `stderr` first before `err.message`, so let's do the same.

**Review by mikeharder — CHANGES_REQUESTED** [review]

File: eng/tools/TypeSpecValidation/src/rules/compile.ts [hunk 6]
```diff
@@ -13,22 +13,24 @@ export class CompileRule implements Rule {
...
-      let [std, err] = await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
-      stdOutput += std;
-      if (err == null) {
+      let [err, stdout, stderr] = await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
+      stdOutput += stdout;
+      if (err) {
         success = false;
-        errorOutput += err;
+        errorOutput += err.message;
+        errorOutput += stderr;
```
Comment (ckairen) [inline eng/tools/TypeSpecValidation/src/rules/compile.ts:21]:
```suggestion
        errorOutput += stderr;
        errorOutput += err.message;
```

File: eng/tools/TypeSpecValidation/src/rules/compile.ts [hunk 7]
```diff
@@ -13,22 +13,24 @@ export class CompileRule implements Rule {
     let errorOutput: string | undefined;
 
     if (await checkFileExists(path.join(folder, "main.tsp"))) {
-      let [std, err] = await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
-      stdOutput += std;
-      if (err == null) {
+      let [err, stdout, stderr] = await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
+      stdOutput += stdout;
+      if (err) {
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/rules/compile.ts:18]:
```suggestion
      stdOutput += stdout;
      errorOutput += stderr;
      if (err) {
```

File: eng/tools/TypeSpecValidation/src/rules/compile.ts [hunk 8]
```diff
@@ -13,22 +13,24 @@ export class CompileRule implements Rule {
...
         success = false;
-        errorOutput += err;
+        errorOutput += stderr;
+        errorOutput += err.message;
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/rules/compile.ts:21]:
```suggestion
        errorOutput += err.message;
```

File: eng/tools/TypeSpecValidation/src/rules/format.ts [hunk 9]
```diff
@@ -8,9 +8,11 @@ export class FormatRule implements Rule {
 
   async execute(folder: string): Promise<RuleResult> {
     // Format parent folder to include shared files
-    let [stdOutput, errorOutput] = await runCmd(`npx tsp format ../**/*.tsp`, folder);
 
-    let success = errorOutput == null ? false : true;
+    let [err, stdOutput, errorOutput] = await runCmd(`npx tsp format ../**/*.tsp`, folder);
+    // Failing on both err and errorOutput because of known bug in tsp format where it returns 0 on failed formatting
+    // https://github.com/microsoft/typespec/issues/2323
+    let success = err || errorOutput ? false : true;
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/rules/format.ts:15]:
```suggestion
    let success = !err && !errorOutput;
```

This is more succinct and I think equivalent?

**Review by mikeharder — CHANGES_REQUESTED** [review]

File: eng/tools/TypeSpecValidation/src/rules/compile.ts [hunk 10]
```diff
@@ -13,22 +13,24 @@ export class CompileRule implements Rule {
     let errorOutput: string | undefined;
 
     if (await checkFileExists(path.join(folder, "main.tsp"))) {
-      let [std, err] = await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
-      stdOutput += std;
-      if (err == null) {
+      let [err, stdout, stderr] = await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
+      stdOutput += stdout;
+      errorOutput += stderr;
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/rules/compile.ts]:
```suggestion
```

**Review by mikeharder — APPROVED** [review]

File: eng/tools/TypeSpecValidation/src/rules/format.ts [hunk 11]
```diff
@@ -8,9 +8,11 @@ export class FormatRule implements Rule {
 
   async execute(folder: string): Promise<RuleResult> {
     // Format parent folder to include shared files
-    let [stdOutput, errorOutput] = await runCmd(`npx tsp format ../**/*.tsp`, folder);
 
-    let success = errorOutput == null ? false : true;
+    let [err, stdOutput, errorOutput] = await runCmd(`npx tsp format ../**/*.tsp`, folder);
+    // Failing on both err and errorOutput because of known bug in tsp format where it returns 0 on failed formatting
+    // https://github.com/microsoft/typespec/issues/2323
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/rules/format.ts:14]:
```suggestion
    // microsoft/typespec#2323
```
