### PR TITLE
Al/tsv noop

### LINKED ISSUE #24813: [typespec - pr] Pipeline fails if PR didn't change any TypeSpec specs
If a PR doesn't change any TypeSpec specs, the `typespec - pr` pipeline should no-op, but its failing instead:

```
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/mnt/vss/_work/_temp/4f8d5da8-e84a-4c41-ba5e-8ee8956b5ab5.ps1'
git -c core.quotepath=off -c i18n.logoutputencoding=utf-8 diff --name-only "origin/main...64f7f5fe49d92fa2396890ce0deb93fc0aaa0a8b" -- | Where-Object {$_.StartsWith('specification')}
Running TypeSpecValidation on folder: undefined
run command:npm prefix
Stdout output:
/mnt/vss/_work/1/s

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^
System.Management.Automation.RemoteException
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=2915833&view=logs&j=2063e0fe-a0a2-55e0-61f7-89c6b872aac9&t=9960aa89-c013-56d4-0ce8-0421b4283180&l=13

### LINKED ISSUE #24818: [Get-TypeSpec-Folders.ps1] Fails on Windows
```
D:\a\_work\1\s\eng\scripts\Get-TypeSpec-Folders.ps1 : The regular expression pattern D:\a\_work\1\s/ is not valid.
```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=2918011&view=logs&j=3e1f1869-f3c0-5969-4002-62fd696d51dd&t=d225ed15-463f-51a4-35b0-edab7571dc30&l=12

### PR DESCRIPTION
**Pull request by ckairen**
closes #24813
closes #24818

### CODE REVIEW

File: eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts [hunk 1]
```diff
@@ -69,7 +69,7 @@ export async function main() {
   }
 
   // Format parent folder to include shared files
-  await runCmd(`npx tsp format ../**/*.tsp`, folder);
+  await runCmd(`npx tsp format ..${path.sep}**${path.sep}*.tsp`, folder);
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts:72]: Is this change necessary?  I would expect `node` commands on Windows to work correctly with forward slashes.

**Review by mikeharder — CHANGES_REQUESTED** [review]

**Comment by mikeharder** [comment]
The failures you saw on Windows are expected for now.  This is #24791, which I will fix after this PR is merged.

File: eng/pipelines/typespec-ci.yml [hunk 2]
```diff
@@ -20,9 +20,19 @@ pr:
 
 jobs:
 - job: Validate_All_Specs
+
+  strategy:
+    matrix:
+      Linux:
+        Pool: azsdk-pool-mms-ubuntu-2204-general
+        OsVmImage: ubuntu-22.04
+      Windows:
```
Comment (weshaggard) [inline eng/pipelines/typespec-ci.yml:29]: @mikeharder do we really think it is worth running this on both OS's all the time? I know there are some odd line-ending issues that we are working through, but I don't think that should have us run these against both every single PR.

File: eng/scripts/Get-TypeSpec-Folders.ps1 [hunk 3]
```diff
@@ -9,8 +9,9 @@ param (
 )
 
 $tspFiles = @()
+$osSlash = [IO.Path]::DirectorySeparatorChar
 if ([string]::IsNullOrEmpty($TargetBranch) -or [string]::IsNullOrEmpty($SourceBranch)) {
-  $tspFiles = (Get-ChildItem -path ./specification tspconfig.yaml -Recurse).FullName -replace "$($pwd.Path)/"
+  $tspFiles = (Get-ChildItem -path ./specification tspconfig.yaml -Recurse).FullName -replace [Regex]::Escape("$($pwd.Path)$osSlash")
```
Comment (weshaggard) [inline eng/scripts/Get-TypeSpec-Folders.ps1:14]: What is the goal here? Is it to get the relative path? If so you can also use the Path APIs for this https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getrelativepath?view=net-7.0

File: eng/pipelines/typespec-ci.yml (hunk 2 above)
Comment (mikeharder) [reply eng/pipelines/typespec-ci.yml:29]: This is the CI pipeline which only runs on CI and scheduled builds, not PRs.  We need at least a nightly signal that development in the repo works on Windows.

Comment (weshaggard) [reply eng/pipelines/typespec-ci.yml:29]: Cool yeah I'm good with the CI one just didn't think it was worth it for PR validation.

File: eng/scripts/Get-TypeSpec-Folders.ps1 (hunk 3 above)
Comment (weshaggard) [reply eng/scripts/Get-TypeSpec-Folders.ps1:14]: To avoid the slash issue in all the places I suggest you simply replacing "\" with "/" the forward. Windows will also work with forward slash paths as well.

File: eng/scripts/Get-TypeSpec-Folders.ps1 [hunk 4]
```diff
@@ -9,8 +9,9 @@ param (
...
 }
 else {
   Write-Host "git -c core.quotepath=off -c i18n.logoutputencoding=utf-8 diff --name-only `"$TargetBranch...$SourceBranch`" -- | Where-Object {`$_.StartsWith('specification')}"
```
Comment (weshaggard) [inline eng/scripts/Get-TypeSpec-Folders.ps1:17]: For this case do we want to scope it to *.tsp or we checking for any files?

File: eng/pipelines/typespec-ci.yml (hunk 2 above)
Comment (mikeharder) [reply eng/pipelines/typespec-ci.yml:29]: Agree it's not worth it for PR validation.

File: eng/scripts/Get-TypeSpec-Folders.ps1 (hunk 4 above)
Comment (mikeharder) [reply eng/scripts/Get-TypeSpec-Folders.ps1:17]: Our heuristic is if **any** file is changed under folder `specification/foo`, we will validate **all** TypeSpec specs under folder `specification/foo`.

It's not sufficient to only check for changes to `*.tsp` files, since changes to `tspconfig.yaml` or AutoRest `*.json` can also cause validation to fail.

It's also not sufficient to only validate specs if a file changed under the folder containing `tspconfig.yaml`, since specs can import other files from sibling folders (and maybe even parent folders).  But we do have guidance for the repo that specs should not import files outside their `specfication/foo` folder.

This may result in validating more specs than are strictly necessary for a PR, but we'd rather err on the side of validating too much than too little.  All specs in main should be passing at all times, since if any spec is failing in main it should be fixed ASAP.

File: eng/scripts/Get-TypeSpec-Folders.ps1 [hunk 5]
```diff
@@ -19,8 +20,10 @@ else {
 
 $typespecFolders = @()
 foreach ($file in $tspFiles) {
-  $file -match 'specification\/[^\/]*\/' | out-null
-  $typespecFolders += (Get-ChildItem -path $matches[0] tspconfig.yaml -Recurse).Directory.FullName -replace "$($pwd.Path)/"
+  $file -match "specification\$osSlash[^\$osSlash]*\$osSlash" | out-null
+  if ($matches) {
+    $typespecFolders += (Get-ChildItem -path $matches[0] tspconfig.yaml -Recurse).Directory.FullName -replace [Regex]::Escape("$($pwd.Path)$osSlash")
+  }
```
Comment (weshaggard) [inline eng/scripts/Get-TypeSpec-Folders.ps1:26]:
```suggestion
  if ($file -match 'specification\/[^\/]*\/') {
    $typespecFolders += (Get-ChildItem -path $matches[0] tspconfig.yaml -Recurse).Directory.FullName -replace [Regex]::Escape("$($pwd.Path)$osSlash")
  }
```

File: eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts (hunk 1 above)
Comment (weshaggard) [reply eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts:72]: I would as well

File: eng/scripts/Validate-TypeSpec.ps1 [hunk 6]
```diff
@@ -11,6 +11,7 @@ param (
 $typespecFolders = @()
 
 $typespecFolders = &"$PSScriptRoot/Get-TypeSpec-Folders.ps1" "$SpecsRepoRootDirectory" "$TargetBranch" "$SourceBranch"
+$typespecFolders = $typespecFolders.Split('',[System.StringSplitOptions]::RemoveEmptyEntries)
```
Comment (weshaggard) [inline eng/scripts/Validate-TypeSpec.ps1:14]: What is the split char there it looks like the empty string.

Comment (weshaggard) [reply eng/scripts/Validate-TypeSpec.ps1:14]: If it is easier you could instead import the other script and call a helper function instead of calling it as a script. That way you could return full lists.

Comment (ckairen) [reply eng/scripts/Validate-TypeSpec.ps1:14]: this removes the empty/null entries in the array

Comment (mikeharder) [reply eng/scripts/Validate-TypeSpec.ps1:14]: @ckairen: Do you think this is something we can/should fix?  We could open an issue to fix in a separate PR if you want.

File: eng/pipelines/typespec-ci.yml
Comment (mikeharder) [inline eng/pipelines/typespec-ci.yml:1]: Please revert changes to this file, since it was only used for validating Windows.  Windows will be enabled in a separate PR.

**Review by mikeharder — CHANGES_REQUESTED** [review]

File: eng/pipelines/typespec-ci.yml [hunk 7]
```diff
@@ -20,9 +20,19 @@ pr:
...
+        Pool: azsdk-pool-mms-win-2022-general
+        OsVmImage: windows-2022
+
```
Comment (ckairen) [inline eng/pipelines/typespec-ci.yml:32]:
```suggestion
```

File: eng/pipelines/typespec-ci.yml [hunk 8]
```diff
@@ -20,9 +20,19 @@ pr:
...
   pool:
-    name: azsdk-pool-mms-ubuntu-2204-general
-    vmImage: ubuntu-22.04
+    name: $(Pool)
+    vmImage: $(OSVmImage)
```
Comment (ckairen) [inline eng/pipelines/typespec-ci.yml:35]:
```suggestion
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04
```

File: eng/scripts/Get-TypeSpec-Folders.ps1 [hunk 9]
```diff
@@ -9,18 +9,21 @@ param (
...
+$sanitizedPwd = $($pwd.path) -replace '\\', '/'
 if ([string]::IsNullOrEmpty($TargetBranch) -or [string]::IsNullOrEmpty($SourceBranch)) {
-  $tspFiles = (Get-ChildItem -path ./specification tspconfig.yaml -Recurse).FullName -replace "$($pwd.Path)/"
+  $tspFiles = (Get-ChildItem -path ./specification tspconfig.yaml -Recurse).Directory.FullName -replace '\\', '/' | ForEach-Object {[IO.Path]::GetRelativePath($sanitizedPwd, $_)}
 }
 else {
   Write-Host "git -c core.quotepath=off -c i18n.logoutputencoding=utf-8 diff --name-only `"$TargetBranch...$SourceBranch`" -- | Where-Object {`$_.StartsWith('specification')}"
   $tspFiles = git -c core.quotepath=off -c i18n.logoutputencoding=utf-8 diff --name-only `"$TargetBranch...$SourceBranch`" -- | Where-Object {$_.StartsWith('specification')}
 }
+$tspFiles -replace '\\', '/'
```
Comment (weshaggard) [inline eng/scripts/Get-TypeSpec-Folders.ps1:20]: I suspect this should be the only place you need to do the slash replacement.

File: eng/scripts/Get-TypeSpec-Folders.ps1 [hunk 10]
```diff
@@ -9,18 +9,21 @@ param (
...
 
 $typespecFolders = @()
 foreach ($file in $tspFiles) {
-  $file -match 'specification\/[^\/]*\/' | out-null
-  $typespecFolders += (Get-ChildItem -path $matches[0] tspconfig.yaml -Recurse).Directory.FullName -replace "$($pwd.Path)/"
+  if ($file -match 'specification\/[^\/]*\/') {
+    $typespecFolders += (Get-ChildItem -path $matches[0] tspconfig.yaml -Recurse).Directory.FullName -replace '\\', '/' | ForEach-Object {[IO.Path]::GetRelativePath($sanitizedPwd, $_)}
```
Comment (weshaggard) [inline eng/scripts/Get-TypeSpec-Folders.ps1:25]: I would do this slash replacement after the getrelativepath calls.

File: eng/pipelines/typespec-ci.yml [hunk 11]
```diff
@@ -20,9 +20,17 @@ pr:
...
 jobs:
 - job: Validate_All_Specs
+  strategy:
+    matrix:
+      Linux:
+        Pool: azsdk-pool-mms-ubuntu-2204-general
+        OsVmImage: ubuntu-22.04
+      Windows:
+        Pool: azsdk-pool-mms-win-2022-general
+        OsVmImage: windows-2022
```
Comment (ckairen) [inline eng/pipelines/typespec-ci.yml:30]:
```suggestion
```

File: eng/pipelines/typespec-ci.yml [hunk 12]
```diff
@@ -21,8 +21,8 @@ pr:
 jobs:
 - job: Validate_All_Specs
   pool:
-    name: azsdk-pool-mms-ubuntu-2204-general
-    vmImage: ubuntu-22.04
+    name: $(Pool)
+    vmImage: $(OSVmImage)
```
Comment (ckairen) [inline eng/pipelines/typespec-ci.yml:25]:
```suggestion
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04
```

**Review by mikeharder — APPROVED** [review]
