### PR TITLE
Set StagedArtifactsFolder to empty if it's undefined

### LINKED ISSUE #13214: Release pipeline failed to publish package while csharp emitter is not defined in tspconfig.yaml
There is no csharp emitter defined in https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dnsresolver/resource-manager/Microsoft.Network/DnsResolver/tspconfig.yaml

Release pipeline shows green for SDK generation but failed in "Publish packages Artifacts" step, details can be found in https://dev.azure.com/azure-sdk/internal/internal%20Team/_build/results?buildId=5536518&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=0104da19-5500-51c6-f9d6-914496a5c500&l=10

Since csharp emitter is not defined, "Generate SDK" should fail instead with missing csharp emitter.

### PR DESCRIPTION
**Pull request by raych1**
Resolved https://github.com/Azure/azure-sdk-tools/issues/13214

[Test Run#1](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5676364&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=a15a4eb1-6861-55a5-be9a-45f2166d3e63)
[Test Run#2](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=5676365&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=0104da19-5500-51c6-f9d6-914496a5c500)

### CODE REVIEW

File: eng/tools/spec-gen-sdk-runner/src/command-helpers.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ export function setPipelineVariables(
     setVsoVariable("PrTitle", prTitle);
     setVsoVariable("PrBody", prBody);
   }
-  setVsoVariable("StagedArtifactsFolder", stagedArtifactsFolder);
+  setVsoVariable("StagedArtifactsFolder", stagedArtifactsFolder ?? "");
```
Comment (mikeharder) [inline eng/tools/spec-gen-sdk-runner/src/command-helpers.ts]: why is this necessary?  does `setVsoVariable()` not like setting a value of `undefined`?

Comment (raych1) [reply eng/tools/spec-gen-sdk-runner/src/command-helpers.ts]: Currently the `undefined` value would cause the publish step be executed [here](https://github.com/Azure/azure-rest-api-specs/blob/59930ee61698523269281dc9df36815620cb3d6e/eng/pipelines/templates/stages/archetype-spec-gen-sdk.yml#L270). It shouldn't be run in this case.

**Review by mikeharder — APPROVED** [review]
