### PR TITLE
[TSV] share a helper to get the last segment of emitter-output-dir

### LINKED ISSUE #38964: [tsv validation] fails for emitter-output-dir when using placeholder like {package-name}
**Current issue**: 
In tspconfig, the emitter-output-dir validation does not pass even when package-name is set correctly to Azure.AI.Projects. The issue occurs because the validation checks the placeholder {package-name} literally instead of resolving it to the actual value.
tspconflig.yaml
```
"@typespec/http-client-csharp":
  emitter-output-dir: "{output-dir}/{service-dir}/{package-name}"
  package-name: Azure.AI.Projects
  api-version: "v1"
 ```

**Expected behavior**:
Validation should succeed after replacing {package-name} with the actual value (Azure.AI.Projects).

**How to Fix**:
add resolveVariables method resolves template variable references (in the format {variableName}) within configuration strings by recursively substituting them with their actual values from multiple configuration sources.

### PR DESCRIPTION
**Pull request by skywing918**
fixes https://github.com/Azure/azure-rest-api-specs/issues/38964
1. resolveVariables method resolves template variable references (in the format {variableName}) within configuration strings by recursively substituting them with their actual values from multiple configuration sources.

```
  "@azure-tools/typespec-ts":
    package-name: "arm-aaa-bbb"
    namespace: "{package-name}"
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
```

2. share a helper(getPackageNameFromEmitterOutputDir) to get the last segment of emitter-output-dir, the rule like:
```
export class TspConfigPythonNamespaceMatchesEmitterOutputDirSubRule extends TspconfigEmitterOptionsSubRuleBase {
  constructor() {
    super("@azure-tools/typespec-python", "emitter-output-dir", "derived from emitter-output-dir");
  }
  protected skip(_: any, folder: string) {
    return skipForDataPlane(folder);
  }
  protected validate(config: any): RuleResult {
    let resolvedSegmentResult = this.getPackageNameFromEmitterOutputDir(config);
    console.log("Derived emitter-output-dir:", resolvedSegmentResult.resolved);
    const derivedNamespace = resolvedSegmentResult.resolved.replace(/-/g, ".");
    const namespaceOption = this.tryFindOption(config, "namespace");
    const namespace = namespaceOption as unknown as undefined | string;
    if (derivedNamespace !== namespace)
      return this.createFailedResult(
        `The value of options.${this.emitterName}.namespace "${namespace}" does not match the value derived from options.${this.emitterName}.emitter-output-dir "${derivedNamespace}"`,
        `Please update "options.${this.emitterName}.namespace" to "${derivedNamespace}" or adjust "options.${this.emitterName}.emitter-output-dir" so the derived namespace matches`,
      );

    return { success: true };
  }
}
```

### CODE REVIEW

File: eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts [hunk 1]
```diff
@@ -118,16 +118,127 @@ class TspconfigEmitterOptionsSubRuleBase extends TspconfigSubRuleBase {
...
-    for (const segment of this.keyToValidate.split(".")) {
+    for (const segment of key.split(".")) {
       if (option && typeof option === "object" && !Array.isArray(option) && segment in option)
         option = option![segment];
       else return undefined;
     }
     return option;
   }
 
+  protected resolveVariables(value: string, config: any): { resolved: string; error?: string } {
```
Comment (MaryGao) [inline eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts]: config: Record<string, any>

Comment (MaryGao) [inline eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts]: move this helper as a function.

**Review by MaryGao — APPROVED** [review]

**Review by MaryGao — APPROVED** [review]

**Comment by raych1** [comment]
@MaryGao you might create a PR to exclude `sdk-tspconfig-validation` related files from the protected file list at [here](https://github.com/Azure/azure-rest-api-specs/blob/213be191bef887e148715fc1b767ecda6fac68d2/.github/workflows/protected-files.yaml#L43) so that the future changes on this rule changes won't need to be force merged. CC: @mikeharder
