### PR TITLE
tsv failed when TypeSpec-Validation return 1

### LINKED ISSUE #9355: Improve tooling to detect incorrect or missing configs in tspconfig.yaml file during Rest API spec review.
For mgmt. SDK, we require the configurations for all 5 tier 1 languages (Java, Python, .NET, JS and GO) to be present in the tspconfig.yaml file.
Here is the sample file:  https://github.com/Azure/azure-rest-api-specs/blob/main/specification/contosowidgetmanager/Contoso.Management/tspconfig.yaml

However, today, most service teams only partially update tspconfig.yaml file when they submit their spec PRs for TypeSpec.
And It caused 2 problems:
1. Additional work needed to update tspconfig.yaml before SDK release.
2. SDK automation may not be triggered for the incorrect tspconfig file so we are not sure the typespec is correct for SDK generation.

We need to improve the tooling to ensure the correctness of tspconfig file.

I will let @lmazuel to comment about the requirement for spec PRs for data plane.

### PR DESCRIPTION
**Pull request by skywing918**
This PR make TSV check required for spec PR.
fix https://github.com/Azure/azure-sdk-tools/issues/9355

### CODE REVIEW

File: eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts [hunk 1]
```diff
@@ -516,7 +516,7 @@ export class SdkTspConfigValidationRule implements Rule {
 
     // NOTE: to avoid huge impact on existing PRs, we always return true with info/warning messages.
     return {
-      success: true,
+      success: success,
```
Comment (wanlwanl) [inline eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts:519]:
```suggestion
      success,
```

File: eng/scripts/TypeSpec-Validation.ps1 [hunk 2]
```diff
@@ -55,6 +55,7 @@ if ($typespecFolders) {
     }
 
     npm exec --no -- tsv $typespecFolder 2>&1 | Write-Host
+    Write-Host "Exit code: $LASTEXITCODE"
```
Comment (wanlwanl) [inline eng/scripts/TypeSpec-Validation.ps1:58]: is this required?

File: eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts [hunk 3]
```diff
@@ -506,7 +506,7 @@ export class SdkTspConfigValidationRule implements Rule {
 
     // NOTE: to avoid huge impact on existing PRs, we always return true with info/warning messages.
```
Comment (wanlwanl) [inline eng/tools/typespec-validation/src/rules/sdk-tspconfig-validation.ts:507]: please remove this comment

**Review by wanlwanl — APPROVED** [review]

**Comment by weshaggard** [comment]
@wanlwanl Why was this merged with tsv failing? Now the TSV all is failing for every spec.
