### PR TITLE
[TypeSpec Validation] Refactor rules into separate classes

### LINKED ISSUE #24743: [TypeSpec Validation] Error message "Generated swagger file does not match swagger file on disk" may be inaccurate
The error message `Generated swagger file does not match swagger file on disk` may be inaccurate, since it is triggered by any `git diff`, not necessarily a diff in the generated swagger.  For example, the diff could result from `npx tsp format`:

https://github.com/Azure/azure-rest-api-specs/blob/d78cd3602348ff5f4249d78b9752438cce5dc646/eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts#L76-L84

### LINKED ISSUE #24983: [TypeSpec Validation] Refactor each rule into a separate "Rule" class
To improve code organization and ease of maintenance, I think the TypeSpecValidation code should be refactored to have each logical rule in a separate class, like the following code sample.

Feel free to change the design as you see fit.  Don't treat the interfaces below as the final word, they were just a rough sketch.

But I think the design should have some elements of:

1. A `Rule` base class / interface
1. A `RuleResult` with at least:
    1. Success (boolean)
    1. Output message
        1. Always optional
        1. Always displayed by rule engine on success or fail
    1. Error message
        1. If success, must be empty
        1. If fail, must be non-null and displayed by rule engine
1. An ordered list of Rule instances that will be executed by the rule engine

```typescript
interface Rule {
  readonly name: string;
  readonly description: string;
  execute(folder: string): Promise<RuleResult>;
}

interface RuleResult {
  readonly success: boolean;
  readonly output?: string;
  readonly error?: string;
}

class NpmPrefixRule implements Rule {
  readonly name = "NpmPrefix";
  readonly description = "Verify spec is using root level package.json";

  async execute(folder: string): Promise<RuleResult> {
    let expected_npm_prefix = process.cwd();
    const actual_npm_prefix = (await runCmd(`npm prefix`, folder)).trim();

    let success = true;
    let output =
      "Expected npm prefix: " + expected_npm_prefix + "\n" +
      "Actual npm prefix: " + actual_npm_prefix;
    let error: string;

    if (expected_npm_prefix !== actual_npm_prefix) {
      success = false;
      error = "TypeSpec folders MUST NOT contain a package.json, and instead MUST rely on the package.json at repo root"
    }

    return {
      success: success,
      output: output,
      error: error
    }
  }
}

class CompileRule implements Rule {
  readonly name = "Compile";
  readonly description = "Compile TypeSpec"

  async execute(folder: string): Promise<RuleResult> {
    let success = true;
    let output = "";
    let error: string;

    if (await checkFileExists(path.join(folder, "main.tsp"))) {
      output += await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
      // TODO: If command returns nonzero exit, set success=false and append to error
    }
    if (await checkFileExists(path.join(folder, "client.tsp"))) {
      output += await runCmd(`npx --no tsp compile client.tsp --no-emit --warn-as-error`, folder);
      // TODO: Set success=false if command returns nonzero exit
    }
    
    return {
      success: success,
      output: output,
      error: error,
    }
  }
}

class GitDiffRule implements Rule {
  readonly name = "GitDiff";
  readonly description = "Checks if previous rules resulted in a git diff"

  async execute(folder: string): Promise<RuleResult> {
    const git = simpleGit();
    let gitStatusIsClean = await (await git.status(["--porcelain"])).isClean();

    let success = true;
    let error: string;

    if (!gitStatusIsClean) {
      success = false;
      error += await git.status();
      error += await git.diff();
    }
    
    return {
      success: success,
      error: error
    }
  }
}

async function main(folder: string) {
  let rules = [
    new NpmPrefixRule(),
    new CompileRule(),
    new GitDiffRule(),
  ];

  let success = true;
  for (let i = 0; i < rules.length; i++) {
    const rule = rules[i];
    console.log("Executing rule: " + rule.name);
    const result = await rule.execute(folder);
    console.log(result.output);
    if (!result.success) {
      success = false;
    }
  }

  if (!success) {
    exit(1);
  }
}
```

### PR DESCRIPTION
**Pull request by ckairen**
closes #24983
closes #24743

### CODE REVIEW

File: eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts [hunk 1]
```diff
@@ -7,6 +7,127 @@ import { simpleGit } from "simple-git";
 
 debug.enable("simple-git");
 
+interface TSVRule {
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts:10]: Please move each interface/class to its own source file

**Review by mikeharder — CHANGES_REQUESTED** [review]

**Comment by ckairen** [comment]
also ran the typespec - all pipeline https://dev.azure.com/azure-sdk/public/_build/results?buildId=2997645&view=results

File: eng/tools/TypeSpecValidation/src/TSVRules/CompileRule.ts
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TSVRules/CompileRule.ts:1]: Let's follow the naming conventions used here:

https://github.com/Azure/typespec-azure/tree/main/packages/typespec-azure-core/src/rules

So this file would be renamed to `rules/compile.ts`.

File: eng/tools/TypeSpecValidation/src/TSVRules/RunCmd.ts
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TSVRules/RunCmd.ts:1]: Move to a class named `src/utils.ts`.

File: eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts [hunk 2]
```diff
@@ -1,41 +1,12 @@
...
-import { access } from "fs/promises";
 import { parseArgs, ParseArgsConfig } from "node:util";
-import path from "path";
-import { simpleGit } from "simple-git";
+import { CompileRule } from "./TSVRules/CompileRule.js";
+import { FormatRule } from "./TSVRules/FormatRule.js";
+import { GitDiffRule } from "./TSVRules/GitDiffRule.js";
+import { NpmPrefixRule } from "./TSVRules/NpmPrefixRule.js";
 
 debug.enable("simple-git");
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts:8]: Move to ctor of `GitDiffRule`, since it's the only class using `simple-git`.

File: eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts [hunk 3]
```diff
@@ -48,39 +19,22 @@ export async function main() {
...
-    );
-    throw new Error(
-      "Expected npm prefix: " + expected_npm_prefix + "\nActual npm prefix: " + actual_npm_prefix
-    );
-  }
-
-  // Spec compilation check
-  if (await checkFileExists(path.join(folder, "main.tsp"))) {
-    await runCmd(`npx --no tsp compile . --warn-as-error`, folder);
+  let TSVRules = [new NpmPrefixRule(), new CompileRule(), new FormatRule(), new GitDiffRule()];
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TypeSpecValidation.ts:22]:
```suggestion
  let rules = [new NpmPrefixRule(), new CompileRule(), new FormatRule(), new GitDiffRule()];
```

File: eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts [hunk 4]
```diff
@@ -0,0 +1,11 @@
+export interface TSVRule {
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts:1]:
```suggestion
export interface Rule {
```

File: eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts [hunk 5]
```diff
@@ -0,0 +1,11 @@
...
+  readonly name: string;
+  readonly description: string;
+  execute(folder?: string): Promise<TSVRuleResult>;
+}
+
+export interface TSVRuleResult {
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts:7]:
```suggestion
export interface RuleResult {
```

File: eng/tools/TypeSpecValidation/src/TSVRules/CompileRule.ts [hunk 6]
```diff
@@ -0,0 +1,47 @@
...
+
+    return {
+      success: success,
+      stdOutput: stdOutput,
+      errorOutput: errorOutput,
+    };
+  }
+}
+
+async function checkFileExists(file: string) {
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TSVRules/CompileRule.ts:43]: Move to `src/utils.ts`.

File: eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts:1]: Move to file `src/rule.ts`.

File: eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts (hunk 5 above)
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/src/TSVRules/TSVRule.ts:7]: Move to `src/rule-result.ts`.

**Review by mikeharder — CHANGES_REQUESTED** [review]

**Comment by ckairen** [comment]
aside from the comments, also renamed the other files to conform to the "typespec-azure" style

**Comment by ckairen** [comment]
ran typespec - all as well: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3003591&view=results

**Review by mikeharder — APPROVED** [review]
