### PR TITLE
[TypeSpec Validation] Must emit "@azure-tools/typespec-autorest" by default

### LINKED ISSUE #25041: [TypeSpec Validation] Fail if tspconfig.yaml does not emit typespec-autorest by default
In the following PR, `tspconfig.yaml` was not emitting `typespec-autorest` by default.  So the PR "passed" TypeSpecValidation since there was no `git diff` after `compile`, but the autorest was not actually validated.

https://github.com/Azure/azure-rest-api-specs/pull/24950#discussion_r1277852125

We might be able to prevent this with the following rule:

> If a folder contains `main.tsp` and `tspconfig.yaml`, it must emit `typepspec-autorest` by default

From case study https://github.com/Azure/azure-rest-api-specs/issues/25040

Another PR hit this issue: https://github.com/Azure/azure-rest-api-specs/pull/26038/files/c6f7d417b5dc9e79582039ba9a9a9b08ae6c2813#diff-36e19a34da72c02afb52563771cd944d3a60c71d305c924f9273df4554d641e1

Even if we try to validate that `tspconfig.yaml` emits `typespec-autorest`, we should also detect and fail on this compiler output:

```
run command:npx --no tsp compile . --warn-as-error
Stdout output:
TypeSpec compiler v0.46.0

Compilation completed successfully.

No emitter was configured, no output was generated. Use `--emit <emitterName>` to pick emitter or specify it in the typespec config.
```

### PR DESCRIPTION
**Pull request by mikeharder**
**Must merge after #26411**

- Specs containing file "main.tsp" must emit "@azure-tools/typespec-autorest" by default
- Also check compiler output for defense-in-depth
- Fixes #25041

### CODE REVIEW

File: eng/tools/TypeSpecValidation/src/rules/emit-autorest.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+    if (mainTspExists) {
+      const configFile = join(folder, "tspconfig.yaml");
+      const configText = await readFile(configFile, "utf8");
+      const config = yamlParse(configText);
+
+      const emit = config.emit;
+      stdOutput += `emit: ${JSON.stringify(emit)}\n`;
+
+      if (!emit?.includes("@azure-tools/typespec-autorest")) {
```
Comment (ckairen) [inline eng/tools/TypeSpecValidation/src/rules/emit-autorest.ts:29]: what if there's no emit at all (emit === null | undefined)

Comment (mikeharder) [reply eng/tools/TypeSpecValidation/src/rules/emit-autorest.ts:29]: If `emit` is `null` or `undefined`, the `?.` operator will short-circuit and return `undefined`, which evaluates to `false`, so the rule will return an error.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

File: eng/tools/TypeSpecValidation/test/tsv-test-host.ts [hunk 2]
```diff
@@ -33,4 +33,20 @@ export class TsvTestHost implements TsvHost {
   async checkFileExists(_file: string): Promise<boolean> {
     return true;
   }
+
+  async readTspConfig(_folder: string): Promise<string> {
+    return `
```
Comment (mikeharder) [inline eng/tools/TypeSpecValidation/test/tsv-test-host.ts:38]:
```suggestion
    // Sample config that should cause all rules to succeed
    return `
```

File: eng/tools/TypeSpecValidation/src/rules/compile.ts [hunk 3]
```diff
@@ -17,6 +17,13 @@ export class CompileRule implements Rule {
         `npx --no tsp compile . --warn-as-error`,
         folder,
       );
+      if (
```
Comment (timotheeguerin) [inline eng/tools/TypeSpecValidation/src/rules/compile.ts:20]: This feels quite fragile. I think it might be good to consider calling the compiler programmatically to get that info reliabilty.

File: eng/tools/TypeSpecValidation/src/rules/emit-autorest.ts [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+  readonly name = "EmitAutorest";
+
+  readonly description = 'Must emit "@azure-tools/typespec-autorest" by default';
+
+  async execute(host: TsvHost, folder: string): Promise<RuleResult> {
+    let success = true;
+    let stdOutput = "";
+    let errorOutput = "";
+
+    const mainTspExists = await host.checkFileExists(join(folder, "main.tsp"));
```
Comment (timotheeguerin) [inline eng/tools/TypeSpecValidation/src/rules/emit-autorest.ts:17]: is this step relevant for this rule?

File: eng/tools/TypeSpecValidation/src/rules/compile.ts (hunk 3 above)
Comment (mikeharder) [reply eng/tools/TypeSpecValidation/src/rules/compile.ts:20]: Do you have an example of how we would call the compiler programmatically instead?  I'm not too worried about the fragility of this specific check, since it should just be defense-in-depth for the `emit-autorest` rule.

File: eng/tools/TypeSpecValidation/src/rules/emit-autorest.ts (hunk 4 above)
Comment (mikeharder) [reply eng/tools/TypeSpecValidation/src/rules/emit-autorest.ts:17]: Yes, because if a spec folder only contains `client.tsp`, it doesn't emit autorest.

File: eng/tools/TypeSpecValidation/src/rules/compile.ts (hunk 3 above)
Comment (timotheeguerin) [reply eng/tools/TypeSpecValidation/src/rules/compile.ts:20]: https://github.com/microsoft/typespec/blob/be937a8b850e945073f8711232c73cc5fc604076/packages/samples/src/sample-snapshot-testing.ts#L89-L111

File: eng/tools/TypeSpecValidation/src/tsv-runner-host.ts [hunk 5]
```diff
@@ -11,6 +13,10 @@ export class TsvRunnerHost implements TsvHost {
     return simpleGit(folder);
   }
 
+  readTspConfig(folder: string): Promise<string> {
+    return readFile(join(folder, "tspconfig.yaml"), "utf-8");
```
Comment (ckairen) [inline eng/tools/TypeSpecValidation/src/tsv-runner-host.ts:17]: do we need error handling when file not found?

File: eng/tools/TypeSpecValidation/test/emit-autorest.ts [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+`;
+
+    const result = await new EmitAutorestRule().execute(host, TsvTestHost.folder);
+
+    assert(result.success);
+  });
+
+  it("should fail if no config", async function () {
+    let host = new TsvTestHost();
+    host.readTspConfig = async (_folder: string) => "";
```
Comment (ckairen) [inline eng/tools/TypeSpecValidation/test/emit-autorest.ts:30]: just want to double check that readfile will return empty string if no file is found

File: eng/tools/TypeSpecValidation/src/tsv-runner-host.ts (hunk 5 above)
Comment (mikeharder) [reply eng/tools/TypeSpecValidation/src/tsv-runner-host.ts:17]: I think it's fine to just throw.  Rule `FolderStructure` should already ensure `tspconfig.yaml` exists.

File: eng/tools/TypeSpecValidation/test/emit-autorest.ts (hunk 6 above)
Comment (mikeharder) [reply eng/tools/TypeSpecValidation/test/emit-autorest.ts:30]: It will throw, but I think it's fine.  Rule `FolderStructure` should already ensure `tspconfig.yaml` exists.

File: eng/tools/TypeSpecValidation/test/emit-autorest.ts [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+emit:
+  - "@azure-tools/typespec-autorest"
+`;
+
+    const result = await new EmitAutorestRule().execute(host, TsvTestHost.folder);
+
+    assert(result.success);
+  });
+
+  it("should fail if no config", async function () {
```
Comment (ckairen) [inline eng/tools/TypeSpecValidation/test/emit-autorest.ts:28]:
```suggestion
  it("should fail if config is empty", async function () {
```

Comment (ckairen) [reply eng/tools/TypeSpecValidation/test/emit-autorest.ts:28]: viewing it as config file exists but doesn't have anything in it

File: eng/tools/TypeSpecValidation/src/rules/compile.ts (hunk 3 above)
Comment (mikeharder) [reply eng/tools/TypeSpecValidation/src/rules/compile.ts:20]: https://github.com/Azure/azure-rest-api-specs/issues/26418

**Review by ckairen — APPROVED** [review]
